### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by ghost** [KaneCheshire/PixelTest#51]
Would be great to have [Carthage](https://github.com/Carthage/Carthage) support.

**Comment by KaneCheshire** [comment]
Good idea, I’ve never actually written a framework that supports Carthage before so not sure what is required but can look into it :)

**Comment by ghost** [comment]
Awesome. It only takes a minute. Just share via git the Xcode scheme used to build your framework target.

Then just add a badge to README declaring 'carthage compatible' so folks know you did it.

```bash
pwd
/Users/robertnash/Desktop/untitled folder
ls 
Cartfile
cat Cartfile
github "KaneCheshire/PixelTest" == 2.0.0
carthage update
*** Cloning PixelTest
*** Checking out PixelTest at "2.0.0"
*** xcodebuild output can be found in /var/folders/vl/630ywf4s62j1ppzyh271sdb80000gn/T/carthage-xcodebuild.Ho6WQe.log
*** Skipped building PixelTest due to the error:
Dependency "PixelTest" has no shared framework schemes
```
