### ISSUE TITLE
Pending release for Xcode 13

### ISSUE THREAD

**Issue by pedroseruca** [KaneCheshire/PixelTest#75]
I have notice that you have fixed the `setUp` ambiguate-selector problem that come up with Xcode 13 update.

Do you plan to make a tag and release a version with that fix?

Anyone that uses this framework currently can't run it on new Xcode version or is limited to point the pod file to the main branch which is not recommended.

**Comment by KaneCheshire** [comment]
Should be available now as 2.3.2 on Cocoapods. I had to run Terminal in Rosetta mode on a brand new M1 Mac to do this 🙃
